version: '3.8'

services:
  tomcat:
    image: tomcat:9.0-jdk11-temurin
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD", "sh", "-c", "exec 3<>/dev/tcp/localhost/8080"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s
    environment:
      CATALINA_BASE: /usr/local/tomcat
    volumes:
      - tomcat-data:/usr/local/tomcat/webapps
      - tomcat-logs:/usr/local/tomcat/logs

volumes:
  tomcat-data:
  tomcat-logs:
