name: Validate Tomcat STIG Baseline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  validate:
    name: Run InSpec profile
    runs-on: ubuntu-latest

    services:
      tomcat:
        image: tomcat:9.0-jdk11-temurin
        options: --health-cmd="sh -c 'exec 3<>/dev/tcp/localhost/8080'" --health-interval=10s --health-timeout=5s --health-retries=5
        ports:
          - 8080:8080

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install cinc-auditor
        run: |
          curl -L https://omnitruck.cinc.sh/install.sh | sudo bash -s -- -P cinc-auditor

      - name: Validate profile syntax
        run: cinc-auditor check .

      - name: Wait for Tomcat to be ready
        run: |
          for attempt in $(seq 1 30); do
            if curl -s http://localhost:8080 > /dev/null 2>&1; then
              echo "Tomcat is ready"
              exit 0
            fi
            sleep 2
          done
          echo "Tomcat failed to start" >&2
          exit 1

      - name: Execute InSpec baseline
        run: |
          cinc-auditor exec . \
            --target "docker://tomcat" \
            --input-file inputs-vanilla.yml \
            --reporter cli \
            --show-progress
